### ISSUE TITLE
在tracing branch 上做 epoll/poll 两种方案的性能对比

### ISSUE THREAD

**Issue by zczjx** [zczjx/posix-bsp-perf#12]
@northbigpanda 
把你的新加change cherry-pick 到 tracing branch 上去
然后用 bspTrace 收集poll/epoll 两种场景下的性能数据，上传到 
https://ui.perfetto.dev/
做性能分析，并把分析图贴出来

**Comment by northbigpanda** [comment]
done, can be found at d1ae097c9657d856f5844bc897c0b132135b2178
