### ISSUE TITLE
将 libevent 库集成到 bsp socket 框架，用基类和API 封装好

### ISSUE THREAD

**Issue by zczjx** [zczjx/posix-bsp-perf#14]
将 libevent 库集成到 bsp socket 框架，用基类和API 封装好

@northbigpanda

**Comment by zczjx** [comment]
程序在运行时 使用如下 tcpdump 命令抓取 lo 网络接口的数据包，在windows 上用 Wireshark 工具分析数据包，过滤出tcp 端口号为 12345 的数据包 @northbigpanda 
`sudo tcpdump -ni lo -w "aio_tcp_epoll.pcap"`

**Comment by zczjx** [comment]
再用如下命令抓取 22端口 ssh 远程登录的数据包，用 Wireshark 分析看有什么不同
‘sudo tcpdump -ni enp34s0 port 22 -w "xxx_ssh.pcap"’

**Comment by northbigpanda** [comment]
1. 运行 sudo tcpdump -ni lo -w "aio_tcp_epoll.pcap"后，过滤出的tcp端口为12346的数据包如下：
![image](https://github.com/user-attachments/assets/75223516-9571-4e58-8c60-058bd4aaff6c)

2. 抓取22端口 ssh远程登陆的数据包，用Wireshark分析后，发现有以下不同：
a. lo接口的数据包之间的延时是微秒级，ssh接口的数据包之间的延时是毫秒级
b. lo接口不通过网卡，不经过数据链路层，所以MAC地址显示为0
c. lo接口的数据包能够看到内容，ssh接口的数据包是加密的，看不到内容
d. ssh接口的数据包更大些，可能是因为加密后数据量变大
e. 在ssh的pcap数据包里面发现了2个client port，查询copilot后，得知是由于我在secureCRT里面开启了2个会话，所以会有两个port

**Comment by northbigpanda** [comment]
> 

done, but cannot run and didn't find the bug.

**Comment by northbigpanda** [comment]
done, the bug was resolved, details can be reviewed in commit 0511ea77cd7a308b180038b4c19ee7579baca040

**Comment by northbigpanda** [comment]
> 将 libevent 库集成到 bsp socket 框架，用基类和API 封装好
> 
> @northbigpanda

done, can be found in commit e3a46d3a7512819c79eb099017f02803784170cb
